### ISSUE TITLE
Dangerous issue with reserve and vector_emplace in vector.h

### ISSUE THREAD

**Issue by HelifeWasTaken** [KaisenAmin/c_std#2]
```cpp
    if (vec->size == vec->capacitySize) {
        vector_reserve(vec, vec->capacitySize * 2); // Use the modified version
    }
    char *base = (char *)vec->items;
    memmove(base + (pos + 1) * vec->itemSize, 
            base + pos * vec->itemSize, 
            (vec->size - pos) * vec->itemSize);
    memcpy(base + pos * vec->itemSize, item, vec->itemSize);
    vec->size++;
```
What is the vector supposed to do when reserve fails this is actually a really dangerous matter as we may overwrite data. There shall be a way to inform the user of problems (other than just printing out a message)

Simply returning a boolean maybe ?

**Comment by KaisenAmin** [comment]
Dear Mattis,

Thank you so much for your valuable input regarding the handling of memory
allocation failures in our Vector implementation. Your concern about the
potential danger of overwriting data due to unhandled allocation failures
was absolutely valid and crucial for the robustness of our data structure.

I'm pleased to inform you that we've updated our Vector code to address
this issue. Now, the vector_reserve function has been modified to return a
boolean value, indicating the success or failure of memory allocation.
