### ISSUE TITLE
Feedback and nice things to implement

### ISSUE THREAD

**Issue by ThalusA** [KaisenAmin/c_std#7]
Do you mind considering using NULL pointer or -1 as return value for when there is an error instead of exit(-1) ? It isn't safe to use with exit(-1) because most of the time we don't want an application to crash because of a simple error even if it's memory related.

But also, is it possible to guard each call to fmt_fprintf with a "#ifdef LOGGING_ENABLE" or "#ifndef LOGGING_DISABLE" ? We don't want all the time printing to stderr libraries error in client applications

**Comment by KaisenAmin** [comment]
Dear ThalusA

If you look at the previous commits, especially in the create functions
They return null.
I changed it to exit because I didn't want to constantly check in the
program whether it was created or not. And secondly, because supposedly, if
the object is not created, the rest of the operation is useless In general,
it was just a decision, but I will definitely check this issue again.

also you are right regarding the display of stderr messages, this issue
should be corrected, or what is better, if you get a chance, do it in the
implementations.

thank you
