### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by luyuduan** [KaisenAmin/c_std#9]
1. Excess duplicate parameters
![image](https://github.com/KaisenAmin/c_std/assets/37297576/563a9fa9-f53b-4e54-a0b9-5fdef0616add)

2. Not including necessary header file path
![image](https://github.com/KaisenAmin/c_std/assets/37297576/60a057ea-198b-411b-a921-9856933472e3)

**Comment by KaisenAmin** [comment]
Ensure OpenSSL is properly installed on the system. For MinGW64, OpenSSL
can often be installed using the package manager that comes with MSYS2
(pacman).
Use the command pacman -S mingw-w64-x86_64-openssl to install OpenSSL.

Verify that the paths to OpenSSL headers and libraries are correct.
The user should update the openssl_include_path and openssl_lib_path
variables to point to the actual paths where OpenSSL headers and libraries
are installed on their system. The paths should be relative to the project
directory or absolute paths.

It's better to add the path to the MinGW64 bin directory to the PATH
environment variable so that the gcc compiler can be found.

For linux :
sudo apt install libssl-dev on Ubuntu.
system paths (/usr/include and /usr/lib or /usr/local/include and
/usr/local/lib). Ensure that these paths are correctly specified in the
script if they are non-standard.
